import 'package:flutter/material.dart';

import '../../athlete_profile/models/athlete_profile.dart';

/// Immutable coaching product in the Plan Library.
///
/// Describes coaching philosophy only — **no workouts**.
/// Daily execution is generated by Coach Brain from an active [PlanAssignment].
///
/// **Legacy / prototype (quarantined):** This generative Plan Library pathway
/// is **not** authoritative programme architecture. Production programmes use
/// `ProgrammeLineage` + immutable `ProgrammeVersion` and the Authored Plan
/// Package (`lib/features/authored_plan_package/`). New Plan Package code must
/// not depend on this type. Existing behaviour remains temporarily supported
/// pending a separately approved migration/removal sprint.
class PlanDefinition {
  const PlanDefinition({
    required this.planId,
    required this.slug,
    required this.name,
    required this.subtitle,
    required this.shortDescription,
    required this.longDescription,
    required this.category,
    required this.primaryGoal,
    required this.recommendedDaysPerWeek,
    required this.typicalSessionDurationMinutes,
    required this.durationWeeks,
    required this.equipmentProfile,
    required this.experienceLevel,
    required this.progressionModel,
    required this.coachingFocus,
    required this.capabilityPriorities,
    required this.whoItsFor,
    required this.whatYouImprove,
    required this.typicalWeekSummary,
    this.supportedGoals = const [],
    this.tags = const [],
    this.coverImagePlaceholder,
    this.colourTheme = const Color(0xFF738864),
    this.version = '1.0.0',
    this.author = 'Cohort',
    this.published = true,
    this.createdAt,
    this.faqs = const [],
  });

  // Identity
  final String planId;
  final String slug;
  final String version;

  // Presentation
  final String name;
  final String subtitle;
  final String shortDescription;
  final String longDescription;
  final String? coverImagePlaceholder;
  final Color colourTheme;
  final List<String> tags;

  // Classification
  final PlanCategory category;
  final AthleteGoalSelection primaryGoal;
  final List<AthleteGoalSelection> supportedGoals;

  // Training shape (product metadata — not session prescriptions)
  final int recommendedDaysPerWeek;
  final int typicalSessionDurationMinutes;
  final int durationWeeks;
  final PlanEquipmentProfile equipmentProfile;
  final AthleteExperienceLevel experienceLevel;

  // Coaching philosophy (high-level; never workouts)
  final String progressionModel;
  final String coachingFocus;
  final List<String> capabilityPriorities;

  // Detail copy for athlete-facing screens
  final String whoItsFor;
  final List<String> whatYouImprove;
  final String typicalWeekSummary;
  final List<PlanFaq> faqs;

  // Metadata
  final String author;
  final bool published;
  final DateTime? createdAt;

  String get goalLabel => primaryGoal.label;
  String get ontologyGoalId => primaryGoal.ontologyGoalId;

  /// Display difficulty derived from experience (card presentation only).
  String get difficultyLabel => switch (experienceLevel) {
    AthleteExperienceLevel.beginner => 'Beginner',
    AthleteExperienceLevel.intermediate => 'Intermediate',
    AthleteExperienceLevel.advanced => 'Advanced',
  };

  String get durationLabel => '$typicalSessionDurationMinutes min';
  String get weeksLabel => '$durationWeeks weeks';
  String get daysLabel => '$recommendedDaysPerWeek days / week';

  String get equipmentSummary => equipmentProfile.summary;

  List<String> get equipmentPresetIds => equipmentProfile.presetIds;
}

/// Equipment requirements for a plan (presets — not workout lists).
class PlanEquipmentProfile {
  const PlanEquipmentProfile({required this.presetIds, this.label});

  final List<String> presetIds;
  final String? label;

  String get summary {
    if (label != null && label!.trim().isNotEmpty) return label!;
    if (presetIds.isEmpty) return 'Flexible';
    return presetIds
        .map(AthleteEquipmentCatalog.byId)
        .map((p) => p.label)
        .join(' · ');
  }
}

enum PlanCategory { race, physique, strength, military, longevity, general }

class PlanFaq {
  const PlanFaq({required this.question, required this.answer});

  final String question;
  final String answer;
}
