**

!packages/
!packages/cohort_plan_package/
!packages/cohort_plan_package/pubspec.yaml
!packages/cohort_plan_package/pubspec.lock
!packages/cohort_plan_package/lib/
!packages/cohort_plan_package/lib/**

!server/
!server/trusted_plan_package_import/
!server/trusted_plan_package_import/pubspec.yaml
!server/trusted_plan_package_import/pubspec.lock
!server/trusted_plan_package_import/lib/
!server/trusted_plan_package_import/lib/**
!server/trusted_plan_package_import/bin/
!server/trusted_plan_package_import/bin/**

**/.env
**/.env.*
**/.git
**/.dart_tool
**/build
**/test
