import '../../../domain/adaptation/adaptation_domain.dart';
import '../../../models/protocol_draft.dart';
import '../../../models/protocol_step_draft.dart';
import '../../../models/session_revision_vocabulary.dart';
import '../../../models/training_content_vocabulary.dart';

/// Canonical Cohort starter session templates (stable seed IDs).
///
/// Source of truth for application fixtures and SQL seed content.
/// Seed IDs use the `TMP-###` public-code pattern (parallel to Cohort Protocols).
class CohortSessionTemplateCatalogue {
  CohortSessionTemplateCatalogue._();

  static const seedIdPrefix = 'TMP-';

  static bool isCanonicalSeedId(String protocolId) {
    final id = protocolId.trim();
    if (!id.startsWith(seedIdPrefix)) return false;
    final suffix = id.substring(seedIdPrefix.length);
    return RegExp(r'^\d{3}$').hasMatch(suffix);
  }

  /// Ordered starter collection (10 templates).
  static List<ProtocolDraft> all() => List.unmodifiable([
    fullBodyStrength,
    upperBodyStrength,
    lowerBodyStrength,
    aerobicConditioning,
    thresholdIntervals,
    hyroxMixedConditioning,
    minimalEquipmentStrength,
    bodyweightSession,
    mobilityRecovery,
    simpleBenchmark,
  ]);

  static ProtocolDraft? byId(String protocolId) {
    final trimmed = protocolId.trim();
    for (final draft in all()) {
      if (draft.protocolId == trimmed) return draft;
    }
    return null;
  }

  static final fullBodyStrength = _template(
    id: 'TMP-001',
    name: 'Full-Body Strength',
    purpose: 'Balanced strength session covering squat, hinge, push, and pull.',
    sessionType: 'Strength',
    primaryCapability: 'Strength',
    durationMin: 55,
    durationCategory: 'Medium',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Barbell, Full Gym',
    suitableFor: 'General Fitness, Strength',
    physiologicalDemand: 'Moderate',
    recoveryCost: 'Moderate',
    primaryIntent: SessionIntent.fullBodyStrength,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '8 min'),
      _step(
        2,
        'Back Squat',
        section: 'Main',
        exerciseId: 'EX-073',
        sets: '4',
        reps: '5',
        rest: '2 min',
        load: 'Working weight',
      ),
      _step(
        3,
        'Romanian Deadlift',
        section: 'Main',
        exerciseId: 'EX-078',
        sets: '3',
        reps: '8',
        rest: '90 sec',
        load: 'Working weight',
      ),
      _step(
        4,
        'Bench Press',
        section: 'Main',
        exerciseId: 'EX-083',
        sets: '3',
        reps: '6',
        rest: '2 min',
        load: 'Working weight',
      ),
      _step(
        5,
        'Chest Supported Row',
        section: 'Main',
        exerciseId: 'EX-090',
        sets: '3',
        reps: '8',
        rest: '90 sec',
        load: 'Working weight',
      ),
      _step(6, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final upperBodyStrength = _template(
    id: 'TMP-002',
    name: 'Upper-Body Strength',
    purpose: 'Press and pull emphasis for upper-body strength development.',
    sessionType: 'Strength',
    primaryCapability: 'Strength',
    durationMin: 50,
    durationCategory: 'Medium',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Barbell, Bench, Full Gym',
    suitableFor: 'General Fitness, Strength',
    physiologicalDemand: 'Moderate',
    recoveryCost: 'Moderate',
    primaryIntent: SessionIntent.upperBodyStrength,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '8 min'),
      _step(
        2,
        'Bench Press',
        section: 'Main',
        exerciseId: 'EX-083',
        sets: '4',
        reps: '5',
        rest: '2 min',
        load: 'Working weight',
      ),
      _step(
        3,
        'Barbell Row',
        section: 'Main',
        exerciseId: 'EX-091',
        sets: '4',
        reps: '6',
        rest: '2 min',
        load: 'Working weight',
      ),
      _step(
        4,
        'Strict Press',
        section: 'Main',
        exerciseId: 'EX-088',
        sets: '3',
        reps: '6',
        rest: '90 sec',
        load: 'Working weight',
      ),
      _step(
        5,
        'Chin Up',
        section: 'Main',
        exerciseId: 'EX-096',
        sets: '3',
        reps: '6-8',
        rest: '90 sec',
      ),
      _step(6, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final lowerBodyStrength = _template(
    id: 'TMP-003',
    name: 'Lower-Body Strength',
    purpose: 'Squat and hinge focus for lower-body strength.',
    sessionType: 'Strength',
    primaryCapability: 'Strength',
    durationMin: 50,
    durationCategory: 'Medium',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Barbell, Full Gym',
    suitableFor: 'General Fitness, Strength',
    physiologicalDemand: 'High',
    recoveryCost: 'High',
    primaryIntent: SessionIntent.lowerBodyStrength,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '8 min'),
      _step(
        2,
        'Back Squat',
        section: 'Main',
        exerciseId: 'EX-073',
        sets: '4',
        reps: '5',
        rest: '2-3 min',
        load: 'Working weight',
      ),
      _step(
        3,
        'Romanian Deadlift',
        section: 'Main',
        exerciseId: 'EX-078',
        sets: '3',
        reps: '6',
        rest: '2 min',
        load: 'Working weight',
      ),
      _step(
        4,
        'Lateral Lunge',
        section: 'Accessory',
        exerciseId: 'EX-098',
        sets: '3',
        reps: '8/side',
        rest: '60 sec',
      ),
      _step(
        5,
        'Standing Calf Raise',
        section: 'Accessory',
        exerciseId: 'EX-125',
        sets: '3',
        reps: '10',
        rest: '60 sec',
      ),
      _step(6, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final aerobicConditioning = _template(
    id: 'TMP-004',
    name: 'Aerobic Conditioning',
    purpose: 'Steady aerobic engine work with controlled intensity.',
    sessionType: 'Conditioning',
    primaryCapability: 'Engine',
    durationMin: 40,
    durationCategory: 'Medium',
    technicalComplexity: 'Beginner',
    environment: 'Gym',
    requiredEquipment: 'Bike Erg, Row Erg',
    optionalEquipment: 'Ski Erg',
    suitableFor: 'General Fitness, Endurance',
    physiologicalDemand: 'Moderate',
    recoveryCost: 'Low',
    primaryIntent: SessionIntent.aerobicConditioning,
    steps: [
      _step(1, 'Easy warm-up', section: 'Warm-up', duration: '5 min'),
      _step(
        2,
        'Steady aerobic block',
        section: 'Main',
        duration: '25 min',
        notes: 'Sustain conversational effort on bike or rower.',
      ),
      _step(3, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final thresholdIntervals = _template(
    id: 'TMP-005',
    name: 'Threshold Intervals',
    purpose: 'Controlled threshold intervals for aerobic capacity.',
    sessionType: 'Intervals',
    primaryCapability: 'Threshold',
    durationMin: 45,
    durationCategory: 'Medium',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Bike Erg, Row Erg',
    suitableFor: 'Endurance, Intermediate',
    physiologicalDemand: 'High',
    recoveryCost: 'Moderate',
    primaryIntent: SessionIntent.threshold,
    runningRequired: false,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '8 min'),
      _step(
        2,
        'Threshold intervals',
        section: 'Main',
        sets: '5',
        duration: '3 min',
        rest: '2 min',
        notes: 'Strong but sustainable effort; quality over pace chasing.',
      ),
      _step(3, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final hyroxMixedConditioning = _template(
    id: 'TMP-006',
    name: 'HYROX Mixed Conditioning',
    purpose:
        'Mixed-modal conditioning with station work and compromised running.',
    sessionType: 'Hybrid',
    primaryCapability: 'Engine',
    durationMin: 50,
    durationCategory: 'Medium',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Sandbag, Wall Ball, Row Erg, Running Shoes',
    suitableFor: 'HYROX, Intermediate',
    physiologicalDemand: 'High',
    recoveryCost: 'High',
    primaryIntent: SessionIntent.hyroxSpecificConditioning,
    runningRequired: true,
    runningReplaceable: true,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '8 min'),
      _step(
        2,
        'Station circuit',
        section: 'Main',
        sets: '4',
        notes:
            'Rotate wall ball, sandbag carry, and rower. Keep transitions deliberate.',
      ),
      _step(
        3,
        'Compromised run or substitute',
        section: 'Main',
        duration: '8-10 min',
        notes: 'Easy-moderate run, or bike/row substitute if needed.',
      ),
      _step(4, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final minimalEquipmentStrength = _template(
    id: 'TMP-007',
    name: 'Minimal Equipment Strength',
    purpose: 'Strength session using dumbbells or kettlebells only.',
    sessionType: 'Strength',
    primaryCapability: 'Strength',
    durationMin: 40,
    durationCategory: 'Medium',
    technicalComplexity: 'Beginner',
    environment: 'Home',
    requiredEquipment: 'Dumbbell, Minimal Kit',
    optionalEquipment: 'Kettlebell',
    suitableFor: 'Travel, General Fitness, Beginner',
    physiologicalDemand: 'Moderate',
    recoveryCost: 'Moderate',
    hotelFriendly: true,
    indoorFriendly: true,
    primaryIntent: SessionIntent.fullBodyStrength,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '5 min'),
      _step(
        2,
        'Goblet squat pattern',
        section: 'Main',
        sets: '3',
        reps: '10',
        rest: '75 sec',
        notes: 'Use a dumbbell or kettlebell.',
      ),
      _step(
        3,
        'Single-arm row',
        section: 'Main',
        sets: '3',
        reps: '10/side',
        rest: '60 sec',
      ),
      _step(
        4,
        'Floor press',
        section: 'Main',
        sets: '3',
        reps: '8',
        rest: '75 sec',
      ),
      _step(
        5,
        'Suitcase carry',
        section: 'Finisher',
        exerciseId: 'EX-102',
        sets: '3',
        distance: '20-30 m/side',
        rest: '60 sec',
      ),
      _step(6, 'Cool-down', section: 'Cool-down', duration: '4 min'),
    ],
  );

  static final bodyweightSession = _template(
    id: 'TMP-008',
    name: 'Bodyweight Session',
    purpose: 'No-equipment strength and movement quality session.',
    sessionType: 'Strength',
    primaryCapability: 'Strength',
    durationMin: 35,
    durationCategory: 'Short',
    technicalComplexity: 'Beginner',
    environment: 'Anywhere',
    requiredEquipment: 'Bodyweight',
    suitableFor: 'Travel, Beginner, General Fitness',
    physiologicalDemand: 'Low',
    recoveryCost: 'Low',
    hotelFriendly: true,
    indoorFriendly: true,
    noiseFriendly: true,
    primaryIntent: SessionIntent.movementQuality,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '5 min'),
      _step(
        2,
        'Squat pattern',
        section: 'Main',
        sets: '3',
        reps: '12',
        rest: '45 sec',
      ),
      _step(
        3,
        'Push-up pattern',
        section: 'Main',
        sets: '3',
        reps: '8-12',
        rest: '45 sec',
      ),
      _step(
        4,
        'Hip hinge / good morning pattern',
        section: 'Main',
        sets: '3',
        reps: '10',
        rest: '45 sec',
      ),
      _step(
        5,
        'Hollow hold',
        section: 'Core',
        exerciseId: 'EX-112',
        sets: '3',
        duration: '20-30 sec',
        rest: '30 sec',
      ),
      _step(6, 'Cool-down', section: 'Cool-down', duration: '4 min'),
    ],
  );

  static final mobilityRecovery = _template(
    id: 'TMP-009',
    name: 'Mobility & Recovery',
    purpose: 'Low-demand mobility and recovery session for reset days.',
    sessionType: 'Recovery',
    primaryCapability: 'Mobility',
    durationMin: 30,
    durationCategory: 'Short',
    technicalComplexity: 'Beginner',
    environment: 'Anywhere',
    requiredEquipment: 'Bodyweight',
    suitableFor: 'Recovery, Travel, Beginner',
    physiologicalDemand: 'Very Low',
    recoveryCost: 'Very Low',
    hotelFriendly: true,
    indoorFriendly: true,
    noiseFriendly: true,
    primaryIntent: SessionIntent.mobility,
    steps: [
      _step(1, 'Breathing reset', section: 'Warm-up', duration: '3 min'),
      _step(
        2,
        'Hip and thoracic mobility circuit',
        section: 'Main',
        duration: '15 min',
        notes: 'Controlled ranges; no forcing end range.',
      ),
      _step(
        3,
        'Bird dog',
        section: 'Main',
        exerciseId: 'EX-115',
        sets: '2',
        reps: '6/side',
      ),
      _step(
        4,
        'Side plank',
        section: 'Main',
        exerciseId: 'EX-116',
        sets: '2',
        duration: '20-30 sec/side',
      ),
      _step(5, 'Closing stretch', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static final simpleBenchmark = _template(
    id: 'TMP-010',
    name: 'Simple Benchmark Test',
    purpose: 'Repeatable mixed benchmark for tracking work capacity over time.',
    sessionType: 'Benchmark',
    primaryCapability: 'Engine',
    durationMin: 25,
    durationCategory: 'Short',
    technicalComplexity: 'Intermediate',
    environment: 'Gym',
    requiredEquipment: 'Pull-up Bar, Bodyweight',
    suitableFor: 'General Fitness, Intermediate',
    physiologicalDemand: 'High',
    recoveryCost: 'Moderate',
    primaryIntent: SessionIntent.workCapacity,
    steps: [
      _step(1, 'Warm-up', section: 'Warm-up', duration: '6 min'),
      _step(
        2,
        'Benchmark: 10-min AMRAP',
        section: 'Main',
        duration: '10 min',
        notes:
            '5 chin-ups, 10 push-ups, 15 air squats. Record total rounds + reps.',
      ),
      _step(3, 'Cool-down', section: 'Cool-down', duration: '5 min'),
    ],
  );

  static ProtocolDraft _template({
    required String id,
    required String name,
    required String purpose,
    required String sessionType,
    required String primaryCapability,
    required int durationMin,
    required String durationCategory,
    required String technicalComplexity,
    required String environment,
    required String requiredEquipment,
    required String suitableFor,
    required String physiologicalDemand,
    required String recoveryCost,
    required SessionIntent primaryIntent,
    required List<ProtocolStepDraft> steps,
    String? optionalEquipment,
    String? secondaryCapability,
    bool? runningRequired,
    bool? runningReplaceable,
    bool? hotelFriendly,
    bool? indoorFriendly,
    bool? noiseFriendly,
  }) {
    return ProtocolDraft(
      protocolId: id,
      name: name,
      purpose: purpose,
      steps: steps,
      published: true,
      contentKind: TrainingContentKind.sessionTemplate,
      authoringScope: TrainingAuthoringScope.cohortGlobal,
      endorsementStatus: TrainingEndorsementStatus.cohortEndorsed,
      ownerId: null,
      organisationId: null,
      programmeVersionId: null,
      sourceContentId: null,
      sourceContentKind: null,
      revisionNumber: 1,
      lifecycleStatus: SessionRevisionLifecycleStatus.published,
      primaryCapability: primaryCapability,
      secondaryCapability: secondaryCapability,
      sessionType: sessionType,
      sessionFormat: sessionType,
      durationMin: durationMin,
      durationCategory: durationCategory,
      physiologicalDemand: physiologicalDemand,
      recoveryCost: recoveryCost,
      technicalComplexity: technicalComplexity,
      environment: environment,
      requiredEquipment: requiredEquipment,
      optionalEquipment: optionalEquipment,
      suitableFor: suitableFor,
      adaptability: 3,
      runningRequired: runningRequired,
      runningReplaceable: runningReplaceable,
      hotelFriendly: hotelFriendly,
      indoorFriendly: indoorFriendly,
      noiseFriendly: noiseFriendly,
      coachingNotes:
          'Starter Cohort template. Customise after Use Template — the source stays unchanged.',
      primarySessionIntent: primaryIntent,
    );
  }

  static ProtocolStepDraft _step(
    int order,
    String title, {
    String? section,
    String? exerciseId,
    String? sets,
    String? reps,
    String? duration,
    String? rest,
    String? load,
    String? distance,
    String? notes,
  }) {
    return ProtocolStepDraft(
      localId: 'seed-step-$order',
      stepOrder: order,
      title: title,
      section: section,
      exerciseId: exerciseId,
      sets: sets,
      reps: reps,
      duration: duration,
      rest: rest,
      load: load,
      distance: distance,
      notes: notes,
      stepType: 'exercise',
      displayStyle: 'standard',
    );
  }
}
