-- Gate AB — Apollo Week 9 Phase III Rebuild & Assess executable protocols. Local disposable DB only.
TRUNCATE sprint12_gate_results;
DO $$
DECLARE v_count integer; v_conflict text;
BEGIN
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W9-%-R1'; PERFORM sprint12_assert_eq('AB','seven_week9_protocols','7',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-9]-.*-R1$'; PERFORM sprint12_assert_eq('AB','sixty_three_apollo_protocols','63',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W9-%-R1' AND authoring_scope='organisation' AND organisation_id='apollo-dogfood' AND lifecycle_status='published' AND published='true' AND published_at IS NOT NULL; PERFORM sprint12_assert_eq('AB','deterministic_protocol_identities','7',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id LEFT JOIN exercises_v2 x ON x.exercise_id=e.exercise_id WHERE b.session_id LIKE 'APOLLO-W9-%-R1' AND x.exercise_id IS NULL; PERFORM sprint12_assert_eq('AB','no_dangling_exercise_references','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE (b.session_id='APOLLO-W9-MON-R1' AND e.exercise_id='EX-095' AND e.prescription @> '{"sets":4,"reps":"4-6","rir":1}'::jsonb) OR (b.session_id='APOLLO-W9-MON-R1' AND e.exercise_id='EX-136' AND e.prescription @> '{"sets":4,"reps":"5-8","rir":"1-2"}'::jsonb) OR (b.session_id='APOLLO-W9-MON-R1' AND e.exercise_id='EX-088' AND e.prescription @> '{"sets":3,"reps":"6-8","rir":"1-2"}'::jsonb) OR (b.session_id='APOLLO-W9-WED-R1' AND e.exercise_id='EX-073' AND e.prescription @> '{"sets":4,"reps":"4-6","rir":"1-2"}'::jsonb) OR (b.session_id='APOLLO-W9-WED-R1' AND e.exercise_id='EX-078' AND e.prescription @> '{"sets":4,"reps":"6-8","rir":"1-2","eccentric_seconds":3,"rom_and_technique_non_negotiable":true}'::jsonb) OR (b.session_id='APOLLO-W9-WED-R1' AND e.exercise_id='EX-101' AND e.prescription @> '{"sets":4,"distance_m":"30-40","load":"heavy"}'::jsonb) OR (b.session_id='APOLLO-W9-FRI-R1' AND e.exercise_id='EX-143' AND e.prescription @> '{"sets":4}'::jsonb) OR (b.session_id='APOLLO-W9-FRI-R1' AND e.exercise_id='EX-138' AND e.prescription @> '{"sets":4}'::jsonb) OR (b.session_id='APOLLO-W9-FRI-R1' AND e.exercise_id='EX-144' AND e.prescription @> '{"sets":3}'::jsonb) OR (b.session_id='APOLLO-W9-FRI-R1' AND e.exercise_id='EX-139' AND e.prescription @> '{"sets":4}'::jsonb); PERFORM sprint12_assert_eq('AB','phase_three_rebuild_volume_and_rir','10',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W9-THU-R1' AND timer_config @> '{"rounds":3,"work_seconds":480,"recovery_seconds":120,"effort":"threshold","rpe":"7-8","total_threshold_seconds":1440}'::jsonb; PERFORM sprint12_assert_eq('AB','three_by_eight_threshold_timer_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W9-THU-R1' AND e.prescription @> '{"rounds":3,"work_seconds":480,"recovery_seconds":120,"record":"pace_each_interval"}'::jsonb; PERFORM sprint12_assert_eq('AB','threshold_execution_recovery_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W9-SAT-R1' AND timer_config @> '{"rounds":3,"between_round_recovery_seconds":90,"target_rpe":"7-8","round_sequence":["EX-131","EX-132","EX-050","EX-009"]}'::jsonb; PERFORM sprint12_assert_eq('AB','three_round_conditioning_timer_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W9-SAT-R1' AND e.execution_group_key='apollo_w9_sat_conditioning' AND e.execution_group_rounds=3 AND ((e.exercise_id='EX-131' AND e.position=1 AND e.prescription @> '{"distance_m":20,"round_position":1}'::jsonb) OR (e.exercise_id='EX-132' AND e.position=2 AND e.prescription @> '{"distance_m":20,"round_position":2}'::jsonb) OR (e.exercise_id='EX-050' AND e.position=3 AND e.prescription @> '{"distance_m":250,"round_position":3}'::jsonb) OR (e.exercise_id='EX-009' AND e.position=4 AND e.prescription @> '{"reps":8,"round_position":4}'::jsonb)); PERFORM sprint12_assert_eq('AB','exact_three_round_execution_grouping','4',v_count::text);
 SELECT count(*) INTO v_count FROM (SELECT protocol_id FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W9-%-R1' GROUP BY protocol_id HAVING count(*)>1) d; PERFORM sprint12_assert_eq('AB','no_duplicate_protocol_identities','0',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-8]-.*-R1$'; PERFORM sprint12_assert_eq('AB','week1_week8_protocol_counts_unchanged','56',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id ~ '^APOLLO-W[1-8]-.*-R1$'; PERFORM sprint12_assert_eq('AB','week1_week8_block_counts_unchanged','150',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id ~ '^APOLLO-W[1-8]-.*-R1$'; PERFORM sprint12_assert_eq('AB','week1_week8_exercise_row_counts_unchanged','323',v_count::text);
 BEGIN INSERT INTO performance_protocols(protocol_id,name) VALUES ('APOLLO-W9-MON-R1','conflicting deterministic Apollo identity'); PERFORM sprint12_record('AB','conflicting_identity_fails_closed','unique violation','no exception',NULL,FALSE);
 EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS v_conflict = MESSAGE_TEXT; PERFORM sprint12_record('AB','conflicting_identity_fails_closed','unique violation','unique violation',NULL,TRUE,v_conflict); END;
END $$;
SELECT gate,case_id,expected,actual,pass FROM sprint12_gate_results WHERE gate='AB' ORDER BY case_id;
SELECT sprint12_fail_if_any_failed();
