-- Gate AA — Apollo Week 8 Phase II Absorb executable protocols. Local disposable DB only.
TRUNCATE sprint12_gate_results;
DO $$
DECLARE v_count integer; v_conflict text;
BEGIN
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W8-%-R1'; PERFORM sprint12_assert_eq('AA','seven_week8_protocols','7',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-8]-.*-R1$'; PERFORM sprint12_assert_eq('AA','fifty_six_apollo_protocols','56',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W8-%-R1' AND authoring_scope='organisation' AND organisation_id='apollo-dogfood' AND lifecycle_status='published' AND published='true' AND published_at IS NOT NULL; PERFORM sprint12_assert_eq('AA','deterministic_protocol_identities','7',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id LEFT JOIN exercises_v2 x ON x.exercise_id=e.exercise_id WHERE b.session_id LIKE 'APOLLO-W8-%-R1' AND x.exercise_id IS NULL; PERFORM sprint12_assert_eq('AA','no_dangling_exercise_references','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE (b.session_id='APOLLO-W8-MON-R1' AND e.exercise_id='EX-095' AND e.prescription @> '{"sets":3,"reps":"4-6","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-MON-R1' AND e.exercise_id='EX-136' AND e.prescription @> '{"sets":3,"reps":"5-8","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-MON-R1' AND e.exercise_id='EX-138' AND e.prescription @> '{"sets":3,"reps":"12-20","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-WED-R1' AND e.exercise_id='EX-073' AND e.prescription @> '{"sets":3,"reps":"4-6","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-WED-R1' AND e.exercise_id='EX-078' AND e.prescription @> '{"sets":3,"reps":"6-8","rir":"2-3","eccentric_seconds":3}'::jsonb) OR (b.session_id='APOLLO-W8-WED-R1' AND e.exercise_id='EX-101' AND e.prescription @> '{"sets":2,"distance_m":"30-40","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-FRI-R1' AND e.exercise_id='EX-143' AND e.prescription @> '{"sets":2,"reps":"10-15","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-FRI-R1' AND e.exercise_id='EX-120' AND e.prescription @> '{"sets":1,"reps":"10-12","rir":"2-3"}'::jsonb) OR (b.session_id='APOLLO-W8-SAT-R1' AND e.exercise_id='EX-079' AND e.prescription @> '{"sets":2,"reps":"3-5","rir":3}'::jsonb); PERFORM sprint12_assert_eq('AA','exact_reduced_fatigue_set_and_rir_prescriptions','9',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id IN ('APOLLO-W8-MON-R1','APOLLO-W8-WED-R1','APOLLO-W8-FRI-R1') AND coaching_notes LIKE 'Approximately 60-70% normal resistance volume%'; PERFORM sprint12_assert_eq('AA','approved_sixty_to_seventy_percent_volume_target','3',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id IN ('APOLLO-W8-MON-R1','APOLLO-W8-WED-R1','APOLLO-W8-FRI-R1') AND e.prescription @> '{"rir":"2-3"}'::jsonb; PERFORM sprint12_assert_eq('AA','all_specified_two_to_three_rir_targets','29',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W8-THU-R1' AND timer_config @> '{"rounds":4,"work_seconds":180,"recovery_seconds":120,"effort":"controlled_approximately_10k","vo2":false}'::jsonb; PERFORM sprint12_assert_eq('AA','controlled_not_vo2_interval_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W8-SAT-R1' AND block_type='conditioning'; PERFORM sprint12_assert_eq('AA','saturday_contains_no_conditioning_block','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE (session_id='APOLLO-W8-TUE-R1' AND timer_config @> '{"work_seconds":3000}'::jsonb) OR (session_id='APOLLO-W8-SUN-R1' AND timer_config @> '{"work_seconds":3900}'::jsonb); PERFORM sprint12_assert_eq('AA','reduced_zone2_timers','2',v_count::text);
 SELECT count(*) INTO v_count FROM (SELECT protocol_id FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W8-%-R1' GROUP BY protocol_id HAVING count(*)>1) d; PERFORM sprint12_assert_eq('AA','no_duplicate_protocol_identities','0',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-7]-.*-R1$'; PERFORM sprint12_assert_eq('AA','week1_week7_protocol_counts_unchanged','49',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id ~ '^APOLLO-W[1-7]-.*-R1$'; PERFORM sprint12_assert_eq('AA','week1_week7_block_counts_unchanged','132',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id ~ '^APOLLO-W[1-7]-.*-R1$'; PERFORM sprint12_assert_eq('AA','week1_week7_exercise_row_counts_unchanged','280',v_count::text);
 BEGIN INSERT INTO performance_protocols(protocol_id,name) VALUES ('APOLLO-W8-MON-R1','conflicting deterministic Apollo identity'); PERFORM sprint12_record('AA','conflicting_identity_fails_closed','unique violation','no exception',NULL,FALSE);
 EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS v_conflict = MESSAGE_TEXT; PERFORM sprint12_record('AA','conflicting_identity_fails_closed','unique violation','unique violation',NULL,TRUE,v_conflict); END;
END $$;
SELECT gate,case_id,expected,actual,pass FROM sprint12_gate_results WHERE gate='AA' ORDER BY case_id;
SELECT sprint12_fail_if_any_failed();
