-- Gate Z — Apollo Week 7 Phase II Overload executable protocols. Local disposable DB only.
TRUNCATE sprint12_gate_results;
DO $$
DECLARE v_count integer; v_conflict text;
BEGIN
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W7-%-R1'; PERFORM sprint12_assert_eq('Z','seven_week7_protocols','7',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-7]-.*-R1$'; PERFORM sprint12_assert_eq('Z','forty_nine_apollo_protocols','49',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W7-%-R1' AND authoring_scope='organisation' AND organisation_id='apollo-dogfood' AND lifecycle_status='published' AND published='true' AND published_at IS NOT NULL; PERFORM sprint12_assert_eq('Z','deterministic_protocol_identities','7',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id LEFT JOIN exercises_v2 x ON x.exercise_id=e.exercise_id WHERE b.session_id LIKE 'APOLLO-W7-%-R1' AND x.exercise_id IS NULL; PERFORM sprint12_assert_eq('Z','no_dangling_exercise_references','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE (b.session_id='APOLLO-W7-MON-R1' AND e.exercise_id='EX-095' AND e.prescription @> '{"sets":4,"later_sets_may_approach_rir":1,"compound_failure":false}'::jsonb) OR (b.session_id='APOLLO-W7-MON-R1' AND e.exercise_id='EX-136' AND e.prescription @> '{"sets":4,"later_sets_may_approach_rir":1,"compound_failure":false}'::jsonb) OR (b.session_id='APOLLO-W7-MON-R1' AND e.exercise_id='EX-138' AND e.prescription @> '{"sets":5,"reps":"12-20"}'::jsonb) OR (b.session_id='APOLLO-W7-MON-R1' AND e.exercise_id='EX-087' AND e.prescription @> '{"sets":4,"reps":"6-10","compound_failure":false}'::jsonb) OR (b.session_id='APOLLO-W7-WED-R1' AND e.exercise_id='EX-073' AND e.prescription @> '{"sets":4,"reps":"4-6","final_set_may_approach_rir":1,"no_grinders":true}'::jsonb) OR (b.session_id='APOLLO-W7-WED-R1' AND e.exercise_id='EX-078' AND e.prescription @> '{"sets":5,"reps":"6-8","final_set_may_approach_rir":1,"eccentric_seconds":3,"no_grinders":true}'::jsonb) OR (b.session_id='APOLLO-W7-WED-R1' AND e.exercise_id='EX-140' AND e.prescription @> '{"sets":4,"reps":"10-15"}'::jsonb) OR (b.session_id='APOLLO-W7-WED-R1' AND e.exercise_id='EX-101' AND e.prescription @> '{"sets":4,"load":"heavy"}'::jsonb) OR (b.session_id='APOLLO-W7-FRI-R1' AND e.exercise_id='EX-143' AND e.prescription @> '{"sets":5,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb) OR (b.session_id='APOLLO-W7-FRI-R1' AND e.exercise_id='EX-138' AND e.prescription @> '{"sets":6,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb) OR (b.session_id='APOLLO-W7-FRI-R1' AND e.exercise_id='EX-144' AND e.prescription @> '{"sets":5,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb) OR (b.session_id='APOLLO-W7-FRI-R1' AND e.exercise_id='EX-139' AND e.prescription @> '{"sets":4,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb); PERFORM sprint12_assert_eq('Z','exact_week7_overload_and_rir','12',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id LIKE 'APOLLO-W7-%-R1' AND e.prescription @> '{"compound_failure":true}'::jsonb; PERFORM sprint12_assert_eq('Z','no_compound_failure_instruction','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W7-THU-R1' AND timer_config @> '{"rounds":7,"work_seconds":180,"recovery_seconds":90,"rpe":"8.5-9","total_quality_seconds":1260}'::jsonb; PERFORM sprint12_assert_eq('Z','seven_by_three_interval_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W7-SAT-R1' AND timer_config @> '{"rounds":4,"between_round_recovery_seconds":90,"target_rpe":"7-8","round_sequence":["EX-131","EX-132","EX-050","EX-009"],"progression":"improve_load_pace_or_transitions_not_rounds"}'::jsonb; PERFORM sprint12_assert_eq('Z','four_round_conditioning_timer_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W7-SAT-R1' AND b.block_type='conditioning' AND e.execution_group_key='apollo_w7_sat_conditioning' AND e.execution_group_rounds=4 AND ((e.exercise_id='EX-131' AND e.position=1 AND e.prescription @> '{"distance_m":20,"round_position":1}'::jsonb) OR (e.exercise_id='EX-132' AND e.position=2 AND e.prescription @> '{"distance_m":20,"round_position":2}'::jsonb) OR (e.exercise_id='EX-050' AND e.position=3 AND e.prescription @> '{"distance_m":250,"round_position":3}'::jsonb) OR (e.exercise_id='EX-009' AND e.position=4 AND e.prescription @> '{"reps":8,"round_position":4}'::jsonb)); PERFORM sprint12_assert_eq('Z','exact_four_round_execution_grouping','4',v_count::text);
 SELECT count(*) INTO v_count FROM (SELECT protocol_id FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W7-%-R1' GROUP BY protocol_id HAVING count(*)>1) d; PERFORM sprint12_assert_eq('Z','no_duplicate_protocol_identities','0',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W[1-6]-.*-R1$'; PERFORM sprint12_assert_eq('Z','week1_week6_protocol_counts_unchanged','42',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id ~ '^APOLLO-W[1-6]-.*-R1$'; PERFORM sprint12_assert_eq('Z','week1_week6_block_counts_unchanged','113',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id ~ '^APOLLO-W[1-6]-.*-R1$'; PERFORM sprint12_assert_eq('Z','week1_week6_exercise_row_counts_unchanged','238',v_count::text);
 BEGIN INSERT INTO performance_protocols(protocol_id,name) VALUES ('APOLLO-W7-MON-R1','conflicting deterministic Apollo identity'); PERFORM sprint12_record('Z','conflicting_identity_fails_closed','unique violation','no exception',NULL,FALSE);
 EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS v_conflict = MESSAGE_TEXT; PERFORM sprint12_record('Z','conflicting_identity_fails_closed','unique violation','unique violation',NULL,TRUE,v_conflict); END;
END $$;
SELECT gate,case_id,expected,actual,pass FROM sprint12_gate_results WHERE gate='Z' ORDER BY case_id;
SELECT sprint12_fail_if_any_failed();
