-- Gate AE — Apollo Week 12 Arrive & Assess executable protocols. Local disposable DB only.
TRUNCATE sprint12_gate_results;
DO $$
DECLARE v_count integer; v_conflict text;
BEGIN
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W12-%-R1'; PERFORM sprint12_assert_eq('AE','seven_week12_protocols','7',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10|11|12)-.*-R1$'; PERFORM sprint12_assert_eq('AE','eighty_four_apollo_protocols','84',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W12-%-R1' AND authoring_scope='organisation' AND organisation_id='apollo-dogfood' AND lifecycle_status='published' AND published='true' AND published_at IS NOT NULL; PERFORM sprint12_assert_eq('AE','deterministic_protocol_identities','7',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id LEFT JOIN exercises_v2 x ON x.exercise_id=e.exercise_id WHERE b.session_id LIKE 'APOLLO-W12-%-R1' AND x.exercise_id IS NULL; PERFORM sprint12_assert_eq('AE','no_dangling_exercise_references','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W12-MON-R1' AND e.exercise_id='EX-095' AND e.prescription @> '{"assessment":"heavy_clean_3rm","reps":3,"standards":["dead_hang","no_kip","chin_clearly_over_bar"],"tracking":["bodyweight","external_load"]}'::jsonb; PERFORM sprint12_assert_eq('AE','weighted_pullup_3rm_standards_and_tracking','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE (b.session_id='APOLLO-W12-MON-R1' AND e.exercise_id='EX-136' AND e.prescription @> '{"sets":1,"reps":5,"rir":1,"role":"top_set"}'::jsonb) OR (b.session_id='APOLLO-W12-WED-R1' AND e.exercise_id='EX-078' AND e.position=2 AND e.prescription @> '{"sets":1,"reps":6,"rir":1,"role":"benchmark","eccentric_seconds":3}'::jsonb) OR (b.session_id='APOLLO-W12-WED-R1' AND e.exercise_id='EX-078' AND e.position=3 AND e.prescription @> '{"sets":2,"reps":6,"load":"lighter_than_benchmark","role":"back_off"}'::jsonb); PERFORM sprint12_assert_eq('AE','incline_and_rdl_benchmark_prescriptions','3',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-TUE-R1' AND timer_config @> '{"duration_seconds":2700,"tracking":["average_hr","average_pace","distance"],"comparison_protocol_id":"APOLLO-W1-TUE-R1","comparison_fields":["average_hr","average_pace","distance"]}'::jsonb; PERFORM sprint12_assert_eq('AE','zone2_week1_comparison_fields','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-THU-R1' AND timer_config @> '{"allowed_modes":["run","bike","swim","incline_walk"],"intensity":"zone_1_to_low_zone_2","quality_running":false,"selection_required":true}'::jsonb; PERFORM sprint12_assert_eq('AE','recovery_mode_options','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-SAT-R1' AND block_type='custom' AND timer_config @> '{"attempts":3,"full_recovery":true,"tracking":["best_distance_m"]}'::jsonb; PERFORM sprint12_assert_eq('AE','broad_jump_best_distance_tracking','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W12-SAT-R1' AND e.exercise_id='EX-149' AND e.prescription @> '{"sets":1,"maximal":true,"standards":["dead_hang","no_kip","strict_reps"],"tracking":["bodyweight"]}'::jsonb; PERFORM sprint12_assert_eq('AE','strict_pullup_standards_bodyweight_tracking','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-SAT-R1' AND timer_config @> '{"distance_m":5000,"effort":"full","pacing":"even","tracking":["finish_time","average_pace","average_hr","peak_hr"],"additional_conditioning":false}'::jsonb; PERFORM sprint12_assert_eq('AE','five_k_all_result_metrics','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-SAT-R1' AND block_type='conditioning'; PERFORM sprint12_assert_eq('AE','saturday_contains_no_conditioning','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W12-SUN-R1' AND (timer_config @> '{"running":true}'::jsonb OR timer_config @> '{"lifting":true}'::jsonb); PERFORM sprint12_assert_eq('AE','sunday_contains_no_lifting_or_running','0',v_count::text);
 SELECT count(*) INTO v_count FROM (SELECT protocol_id FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W12-%-R1' GROUP BY protocol_id HAVING count(*)>1) d; PERFORM sprint12_assert_eq('AE','no_duplicate_protocol_identities','0',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10|11)-.*-R1$'; PERFORM sprint12_assert_eq('AE','week1_week11_protocol_counts_unchanged','77',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10|11)-.*-R1$'; PERFORM sprint12_assert_eq('AE','week1_week11_block_counts_unchanged','207',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10|11)-.*-R1$'; PERFORM sprint12_assert_eq('AE','week1_week11_exercise_row_counts_unchanged','917',v_count::text);
 BEGIN INSERT INTO performance_protocols(protocol_id,name) VALUES ('APOLLO-W12-MON-R1','conflicting deterministic Apollo identity'); PERFORM sprint12_record('AE','conflicting_identity_fails_closed','unique violation','no exception',NULL,FALSE);
 EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS v_conflict = MESSAGE_TEXT; PERFORM sprint12_record('AE','conflicting_identity_fails_closed','unique violation','unique violation',NULL,TRUE,v_conflict); END;
END $$;
SELECT gate,case_id,expected,actual,pass FROM sprint12_gate_results WHERE gate='AE' ORDER BY case_id;
SELECT sprint12_fail_if_any_failed();
