-- Gate AD — Apollo Week 11 Peak Apollo Performance executable protocols. Local disposable DB only.
TRUNCATE sprint12_gate_results;
DO $$
DECLARE v_count integer; v_conflict text;
BEGIN
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W11-%-R1'; PERFORM sprint12_assert_eq('AD','seven_week11_protocols','7',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10|11)-.*-R1$'; PERFORM sprint12_assert_eq('AD','seventy_seven_apollo_protocols','77',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W11-%-R1' AND authoring_scope='organisation' AND organisation_id='apollo-dogfood' AND lifecycle_status='published' AND published='true' AND published_at IS NOT NULL; PERFORM sprint12_assert_eq('AD','deterministic_protocol_identities','7',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id LEFT JOIN exercises_v2 x ON x.exercise_id=e.exercise_id WHERE b.session_id LIKE 'APOLLO-W11-%-R1' AND x.exercise_id IS NULL; PERFORM sprint12_assert_eq('AD','no_dangling_exercise_references','0',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE (b.session_id='APOLLO-W11-MON-R1' AND e.exercise_id='EX-095' AND e.prescription @> '{"sets":4,"reps":"3-5","rir":1}'::jsonb) OR (b.session_id='APOLLO-W11-MON-R1' AND e.exercise_id='EX-136' AND e.prescription @> '{"sets":4,"reps":"4-6","rir":1}'::jsonb) OR (b.session_id='APOLLO-W11-FRI-R1' AND e.exercise_id='EX-138' AND e.prescription @> '{"sets":5,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb) OR (b.session_id='APOLLO-W11-FRI-R1' AND e.exercise_id='EX-139' AND e.prescription @> '{"sets":4,"final_set_may_approach_rir":"0-1","excellent_technique_required":true}'::jsonb); PERFORM sprint12_assert_eq('AD','exact_peak_strength_and_isolation_progression','4',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W11-THU-R1' AND timer_config @> '{"rounds":6,"work_seconds":180,"recovery_seconds":90,"rpe":"8.5-9","vo2":true,"total_quality_seconds":1080}'::jsonb; PERFORM sprint12_assert_eq('AD','six_by_three_vo2_timer_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id='APOLLO-W11-SAT-R1' AND timer_config @> '{"rounds":4,"between_round_recovery_seconds":90,"target_rpe":"7-8","round_sequence":["EX-131","EX-132","EX-050","EX-009"],"progression":"improve_execution_quality_no_fifth_round"}'::jsonb; PERFORM sprint12_assert_eq('AD','exactly_four_rounds_no_fifth_timer_fidelity','1',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id='APOLLO-W11-SAT-R1' AND e.execution_group_key='apollo_w11_sat_conditioning' AND e.execution_group_rounds=4 AND ((e.exercise_id='EX-131' AND e.position=1 AND e.prescription @> '{"distance_m":20,"round_position":1}'::jsonb) OR (e.exercise_id='EX-132' AND e.position=2 AND e.prescription @> '{"distance_m":20,"round_position":2}'::jsonb) OR (e.exercise_id='EX-050' AND e.position=3 AND e.prescription @> '{"distance_m":250,"round_position":3}'::jsonb) OR (e.exercise_id='EX-009' AND e.position=4 AND e.prescription @> '{"reps":8,"round_position":4}'::jsonb)); PERFORM sprint12_assert_eq('AD','exact_four_round_execution_grouping','4',v_count::text);
 SELECT count(*) INTO v_count FROM (SELECT protocol_id FROM performance_protocols WHERE protocol_id LIKE 'APOLLO-W11-%-R1' GROUP BY protocol_id HAVING count(*)>1) d; PERFORM sprint12_assert_eq('AD','no_duplicate_protocol_identities','0',v_count::text);
 SELECT count(*) INTO v_count FROM performance_protocols WHERE protocol_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10)-.*-R1$'; PERFORM sprint12_assert_eq('AD','week1_week10_protocol_counts_unchanged','70',v_count::text);
 SELECT count(*) INTO v_count FROM session_blocks WHERE session_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10)-.*-R1$'; PERFORM sprint12_assert_eq('AD','week1_week10_block_counts_unchanged','188',v_count::text);
 SELECT count(*) INTO v_count FROM session_block_exercises e JOIN session_blocks b ON b.block_id=e.block_id WHERE b.session_id ~ '^APOLLO-W(1|2|3|4|5|6|7|8|9|10)-.*-R1$'; PERFORM sprint12_assert_eq('AD','week1_week10_exercise_row_counts_unchanged','407',v_count::text);
 BEGIN INSERT INTO performance_protocols(protocol_id,name) VALUES ('APOLLO-W11-MON-R1','conflicting deterministic Apollo identity'); PERFORM sprint12_record('AD','conflicting_identity_fails_closed','unique violation','no exception',NULL,FALSE);
 EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS v_conflict = MESSAGE_TEXT; PERFORM sprint12_record('AD','conflicting_identity_fails_closed','unique violation','unique violation',NULL,TRUE,v_conflict); END;
END $$;
SELECT gate,case_id,expected,actual,pass FROM sprint12_gate_results WHERE gate='AD' ORDER BY case_id;
SELECT sprint12_fail_if_any_failed();
