import 'package:flutter/material.dart';

import '../../athlete_profile/models/athlete_profile.dart';
import '../models/plan.dart';

/// In-memory published plan catalog (no persistence).
class PlanCatalog {
  const PlanCatalog._();

  static List<Plan> get published =>
      all.where((p) => p.status == PlanStatus.published).toList(growable: false);

  static Plan? byId(String planId) {
    for (final plan in all) {
      if (plan.planId == planId) return plan;
    }
    return null;
  }

  static final List<Plan> all = [
    Plan(
      planId: 'plan.hyrox_race_ready',
      name: 'HYROX Race Ready',
      subtitle: 'Stations, pacing, and durable engine work.',
      description:
          'A race-focused plan that builds aerobic capacity, station skill, '
          'and the strength endurance HYROX demands — personalised each session '
          'by Cohort\'s coaching engine.',
      primaryGoal: AthleteGoalCatalog.byId('hyrox'),
      category: PlanCategory.race,
      difficulty: PlanDifficulty.intermediate,
      recommendedDaysPerWeek: 4,
      typicalSessionDurationMinutes: 60,
      equipmentPresetIds: const ['commercial_gym'],
      experience: AthleteExperienceLevel.intermediate,
      whoItsFor:
          'Athletes preparing for HYROX who already train consistently and '
          'want structured race emphasis without programming complexity.',
      whatYouImprove: const [
        'Aerobic capacity and threshold',
        'Station strength endurance',
        'Race pacing under fatigue',
      ],
      typicalWeekSummary:
          'Four sessions mixing engine work, station practice, and recovery '
          'volume — intensity shaped by your profile each day.',
      tags: const ['hyrox', 'race', 'conditioning'],
      colourTheme: const Color(0xFF7A8B62),
      faqs: const [
        PlanFaq(
          question: 'Do I need a full gym?',
          answer:
              'A commercial gym is recommended for station-ready loading. '
              'Cohort adapts movements to your available equipment.',
        ),
        PlanFaq(
          question: 'When are sessions created?',
          answer:
              'Each day\'s session is generated by the coaching engine from '
              'your active plan and profile — not a fixed template workout.',
        ),
      ],
    ),
    Plan(
      planId: 'plan.fat_loss_foundation',
      name: 'Fat Loss Foundation',
      subtitle: 'Strength that protects progress.',
      description:
          'Sustainable conditioning with relative strength and movement '
          'quality — built for athletes who want fat loss without losing '
          'capability.',
      primaryGoal: AthleteGoalCatalog.byId('fat_loss'),
      category: PlanCategory.physique,
      difficulty: PlanDifficulty.beginner,
      recommendedDaysPerWeek: 3,
      typicalSessionDurationMinutes: 45,
      equipmentPresetIds: const ['home_gym', 'commercial_gym', 'minimal'],
      experience: AthleteExperienceLevel.beginner,
      whoItsFor:
          'Beginners and returning athletes who want clear structure and '
          'honest session lengths.',
      whatYouImprove: const [
        'Relative strength',
        'Work capacity',
        'Movement competency',
      ],
      typicalWeekSummary:
          'Three focused sessions with optional recovery emphasis on lighter days.',
      tags: const ['fat_loss', 'foundation', 'beginner'],
      colourTheme: const Color(0xFF96A872),
      faqs: const [
        PlanFaq(
          question: 'Can I train at home?',
          answer:
              'Yes — home gym and minimal equipment are supported. The engine '
              'selects movements that fit your environment.',
        ),
      ],
    ),
    Plan(
      planId: 'plan.military_selection',
      name: 'Military Selection Prep',
      subtitle: 'Strength, carry capacity, and aerobic base.',
      description:
          'Selection-oriented preparation emphasising pushing and pulling '
          'strength, loaded capacity, and durable aerobic work.',
      primaryGoal: AthleteGoalCatalog.byId('military'),
      category: PlanCategory.military,
      difficulty: PlanDifficulty.advanced,
      recommendedDaysPerWeek: 5,
      typicalSessionDurationMinutes: 60,
      equipmentPresetIds: const ['commercial_gym'],
      experience: AthleteExperienceLevel.advanced,
      whoItsFor:
          'Athletes preparing for military selection standards who can commit '
          'to higher weekly volume.',
      whatYouImprove: const [
        'Pushing and pulling strength',
        'Loaded carry capacity',
        'Aerobic resilience',
      ],
      typicalWeekSummary:
          'Five sessions balancing strength, capacity, and recovery posture.',
      tags: const ['military', 'selection', 'strength'],
      colourTheme: const Color(0xFF5E6D4F),
    ),
    Plan(
      planId: 'plan.general_fitness',
      name: 'General Fitness Loop',
      subtitle: 'Balanced strength, capacity, and movement.',
      description:
          'A well-rounded plan for athletes who want consistent training '
          'without a single race or selection target.',
      primaryGoal: AthleteGoalCatalog.byId('general_fitness'),
      category: PlanCategory.general,
      difficulty: PlanDifficulty.intermediate,
      recommendedDaysPerWeek: 4,
      typicalSessionDurationMinutes: 45,
      equipmentPresetIds: const ['commercial_gym', 'home_gym'],
      experience: AthleteExperienceLevel.intermediate,
      whoItsFor:
          'Busy athletes who want balanced fitness and flexible equipment.',
      whatYouImprove: const [
        'Overall work capacity',
        'Strength balance',
        'Sustainable training habit',
      ],
      typicalWeekSummary:
          'Four sessions rotating strength emphasis and conditioning.',
      tags: const ['general', 'balanced'],
      colourTheme: const Color(0xFF738864),
    ),
    Plan(
      planId: 'plan.strength_emphasis',
      name: 'Strength Emphasis',
      subtitle: 'Resilient force with clean movement.',
      description:
          'Prioritises relative strength and movement quality while keeping '
          'enough capacity work to stay athletic.',
      primaryGoal: AthleteGoalCatalog.byId('strength'),
      category: PlanCategory.strength,
      difficulty: PlanDifficulty.intermediate,
      recommendedDaysPerWeek: 4,
      typicalSessionDurationMinutes: 55,
      equipmentPresetIds: const ['commercial_gym', 'home_gym'],
      experience: AthleteExperienceLevel.intermediate,
      whoItsFor:
          'Athletes who want strength as the primary adaptation without '
          'abandoning conditioning.',
      whatYouImprove: const [
        'Relative and absolute strength',
        'Movement quality under load',
        'Session focus and recovery balance',
      ],
      typicalWeekSummary:
          'Four sessions with primary strength development and supporting capacity.',
      tags: const ['strength'],
      colourTheme: const Color(0xFFA8B584),
    ),
    Plan(
      planId: 'plan.longevity',
      name: 'Longevity Base',
      subtitle: 'Train for decades.',
      description:
          'Capacity, strength, and recovery balance for athletes investing in '
          'long-term health and performance.',
      primaryGoal: AthleteGoalCatalog.byId('longevity'),
      category: PlanCategory.longevity,
      difficulty: PlanDifficulty.beginner,
      recommendedDaysPerWeek: 3,
      typicalSessionDurationMinutes: 40,
      equipmentPresetIds: const ['home_gym', 'minimal', 'outdoor'],
      experience: AthleteExperienceLevel.beginner,
      whoItsFor:
          'Athletes who value consistency, recovery, and sustainable intensity.',
      whatYouImprove: const [
        'Movement competency',
        'Aerobic base',
        'Sustainable strength',
      ],
      typicalWeekSummary:
          'Three moderate sessions with recovery-friendly posture.',
      tags: const ['longevity', 'recovery'],
      colourTheme: const Color(0xFF667A58),
    ),
  ];
}
