-- Founder Exercise Library Wave 1 (canonical Cohort catalogue expansion)
-- Idempotent: skip rows that already exist by exercise_id or slug.

INSERT INTO exercises_v2 (
  exercise_id, name, slug, published, category, movement_pattern, equipment,
  primary_muscles, primary_capability, loading_options, purpose
) VALUES
  ('EX-073', 'Back Squat', 'back-squat', true, 'Squat', 'Squat', 'Barbell, Full Gym', 'Quadriceps, Glutes, Hamstrings', 'Strength', 'Load, Reps, RPE, Tempo', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-074', 'Front Squat', 'front-squat', true, 'Squat', 'Squat', 'Barbell, Full Gym', 'Quadriceps, Glutes, Core', 'Strength', 'Load, Reps, RPE, Tempo', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-075', 'Zercher Squat', 'zercher-squat', true, 'Squat', 'Squat', 'Barbell, Full Gym', 'Quadriceps, Glutes, Core', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-076', 'Box Squat', 'box-squat', true, 'Squat', 'Squat', 'Barbell, Box, Full Gym', 'Quadriceps, Glutes, Hamstrings', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-077', 'Safety Bar Squat', 'safety-bar-squat', true, 'Squat', 'Squat', 'Safety Bar, Full Gym', 'Quadriceps, Glutes, Hamstrings', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-078', 'Romanian Deadlift', 'romanian-deadlift', true, 'Hinge', 'Hinge', 'Barbell, Full Gym', 'Hamstrings, Glutes', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-079', 'Trap Bar Deadlift', 'trap-bar-deadlift', true, 'Hinge', 'Hinge', 'Trap Bar, Full Gym', 'Hamstrings, Glutes, Quadriceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-080', 'Single Leg Romanian Deadlift', 'single-leg-romanian-deadlift', true, 'Hinge', 'Hinge', 'Dumbbell or Kettlebell', 'Hamstrings, Glutes', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-081', 'Hip Thrust', 'hip-thrust', true, 'Hinge', 'Hinge', 'Barbell, Bench', 'Glutes, Hamstrings', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-082', 'Good Morning', 'good-morning', true, 'Hinge', 'Hinge', 'Barbell, Full Gym', 'Hamstrings, Glutes, Erector Spinae', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-083', 'Bench Press', 'bench-press', true, 'Push', 'Horizontal Push', 'Barbell, Bench, Full Gym', 'Chest, Triceps, Shoulders', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-084', 'Incline Dumbbell Press', 'incline-dumbbell-press', true, 'Push', 'Horizontal Push', 'Bench, Dumbbells', 'Chest, Shoulders, Triceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-085', 'Weighted Push Up', 'weighted-push-up', true, 'Push', 'Horizontal Push', 'Bodyweight, Weight Vest or Plate', 'Chest, Triceps, Shoulders', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-086', 'Dip', 'dip', true, 'Push', 'Vertical Push', 'Parallel Bars or Rings', 'Chest, Triceps, Shoulders', 'Strength', 'Reps, Load, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-087', 'Weighted Dip', 'weighted-dip', true, 'Push', 'Vertical Push', 'Parallel Bars, Weight Belt', 'Chest, Triceps, Shoulders', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-088', 'Strict Press', 'strict-press', true, 'Push', 'Vertical Push', 'Barbell, Full Gym', 'Shoulders, Triceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-089', 'Landmine Press', 'landmine-press', true, 'Push', 'Vertical Push', 'Barbell, Landmine', 'Shoulders, Chest, Triceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-090', 'Chest Supported Row', 'chest-supported-row', true, 'Pull', 'Horizontal Pull', 'Chest Supported Row Machine or Bench', 'Lats, Rhomboids, Biceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-091', 'Barbell Row', 'barbell-row', true, 'Pull', 'Horizontal Pull', 'Barbell, Full Gym', 'Lats, Rhomboids, Biceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-092', 'Cable Row', 'cable-row', true, 'Pull', 'Horizontal Pull', 'Cable Machine', 'Lats, Rhomboids, Biceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-093', 'Ring Row', 'ring-row', true, 'Pull', 'Horizontal Pull', 'Gymnastic Rings', 'Lats, Rhomboids, Biceps', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-094', 'Face Pull', 'face-pull', true, 'Pull', 'Horizontal Pull', 'Cable, Rope Attachment', 'Rear Delts, Rotator Cuff, Upper Back', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-095', 'Weighted Pull Up', 'weighted-pull-up', true, 'Pull', 'Vertical Pull', 'Pull-up Bar, Weight Belt', 'Lats, Biceps, Core', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-096', 'Chin Up', 'chin-up', true, 'Pull', 'Vertical Pull', 'Pull-up Bar', 'Lats, Biceps', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-097', 'Weighted Chin Up', 'weighted-chin-up', true, 'Pull', 'Vertical Pull', 'Pull-up Bar, Weight Belt', 'Lats, Biceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-098', 'Lateral Lunge', 'lateral-lunge', true, 'Lunge', 'Lunge', 'Dumbbell or Kettlebell (optional)', 'Glutes, Adductors, Quadriceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-099', 'Cossack Squat', 'cossack-squat', true, 'Squat', 'Squat', 'Bodyweight or Kettlebell', 'Glutes, Adductors, Quadriceps', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-100', 'Single Leg Squat', 'single-leg-squat', true, 'Squat', 'Squat', 'Bench or Box (optional)', 'Quadriceps, Glutes', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-101', 'Farmer Carry', 'farmer-carry', true, 'Carry', 'Carry', 'Dumbbells, Kettlebells, or Handles', 'Grip, Core, Traps', 'Strength', 'Load, Distance, Time', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-102', 'Suitcase Carry', 'suitcase-carry', true, 'Carry', 'Carry', 'Dumbbell or Kettlebell', 'Core, Grip, Obliques', 'Strength', 'Load, Distance, Time', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-103', 'Front Rack Carry', 'front-rack-carry', true, 'Carry', 'Carry', 'Dumbbells, Kettlebells, or Barbell', 'Core, Upper Back, Grip', 'Strength', 'Load, Distance, Time', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-104', 'Zercher Carry', 'zercher-carry', true, 'Carry', 'Carry', 'Barbell', 'Core, Biceps, Upper Back', 'Strength', 'Load, Distance, Time', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-105', 'Waiter Carry', 'waiter-carry', true, 'Carry', 'Carry', 'Dumbbell or Kettlebell', 'Shoulders, Core, Grip', 'Strength', 'Load, Distance, Time', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-106', 'Ring Push Up', 'ring-push-up', true, 'Push', 'Horizontal Push', 'Gymnastic Rings', 'Chest, Triceps, Shoulders', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-107', 'Ring Dip', 'ring-dip', true, 'Push', 'Vertical Push', 'Gymnastic Rings', 'Chest, Triceps, Shoulders', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-108', 'Handstand Push Up', 'handstand-push-up', true, 'Push', 'Vertical Push', 'Wall or Freestanding', 'Shoulders, Triceps, Core', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-109', 'Muscle Up', 'muscle-up', true, 'Pull', 'Vertical Pull', 'Pull-up Bar or Rings', 'Lats, Chest, Triceps, Core', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-110', 'Toes to Bar', 'toes-to-bar', true, 'Core', 'Core', 'Pull-up Bar', 'Abdominals, Hip Flexors', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-111', 'Dead Hang', 'dead-hang', true, 'Pull', 'Vertical Pull', 'Pull-up Bar', 'Grip, Lats, Shoulders', 'Strength', 'Time, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-112', 'Hollow Hold', 'hollow-hold', true, 'Core', 'Core', 'Bodyweight', 'Abdominals', 'Strength', 'Time, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-113', 'Ab Wheel Rollout', 'ab-wheel-rollout', true, 'Core', 'Core', 'Ab Wheel', 'Abdominals, Lats', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-114', 'Pallof Press', 'pallof-press', true, 'Core', 'Core', 'Cable, Band', 'Obliques, Core', 'Strength', 'Load, Reps, Time, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-115', 'Bird Dog', 'bird-dog', true, 'Core', 'Core', 'Bodyweight', 'Core, Glutes', 'Strength', 'Reps, Time', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-116', 'Side Plank', 'side-plank', true, 'Core', 'Core', 'Bodyweight', 'Obliques, Core', 'Strength', 'Time, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-117', 'Copenhagen Plank', 'copenhagen-plank', true, 'Core', 'Core', 'Bench', 'Adductors, Obliques, Core', 'Strength', 'Time, RPE', 'Canonical Cohort Wave 1 movement (Unilateral).'),
  ('EX-118', 'Hanging Knee Raise', 'hanging-knee-raise', true, 'Core', 'Core', 'Pull-up Bar', 'Abdominals, Hip Flexors', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-119', 'Hanging Leg Raise', 'hanging-leg-raise', true, 'Core', 'Core', 'Pull-up Bar', 'Abdominals, Hip Flexors', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-120', 'Incline Dumbbell Curl', 'incline-dumbbell-curl', true, 'Pull', 'Horizontal Pull', 'Bench, Dumbbells', 'Biceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-121', 'Rope Triceps Pushdown', 'rope-triceps-pushdown', true, 'Push', 'Horizontal Push', 'Cable, Rope', 'Triceps', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-122', 'Nordic Curl', 'nordic-curl', true, 'Hinge', 'Hinge', 'Bodyweight, Anchor', 'Hamstrings', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-123', 'Back Extension', 'back-extension', true, 'Hinge', 'Hinge', 'Back Extension Bench', 'Erector Spinae, Glutes', 'Strength', 'Reps, Load, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-124', 'Glute Ham Raise', 'glute-ham-raise', true, 'Hinge', 'Hinge', 'GHD Machine', 'Hamstrings, Glutes', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-125', 'Standing Calf Raise', 'standing-calf-raise', true, 'Lower Leg', 'Locomotion', 'Machine or Step', 'Calves', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-126', 'Seated Calf Raise', 'seated-calf-raise', true, 'Lower Leg', 'Locomotion', 'Seated Calf Machine', 'Calves', 'Strength', 'Load, Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).'),
  ('EX-127', 'Tibialis Raise', 'tibialis-raise', true, 'Lower Leg', 'Locomotion', 'Tib Bar or Wall', 'Tibialis Anterior', 'Strength', 'Reps, RPE', 'Canonical Cohort Wave 1 movement (Bilateral).')
ON CONFLICT (exercise_id) DO NOTHING;

-- Prevent duplicate slugs if re-applied after partial insert
-- (requires unique index on slug; safe no-op otherwise)
